### ISSUE TITLE
[feature request] return max possible display size

### ISSUE THREAD

**Issue by piotrcurious** [ArminJo/Arduino-BlueDisplay#20]
Currently display size is hard wired by setFlagsAndSize
It would be nice if size would be returned by android app so the functions getMaxDisplaySize would actually return max possible size.

**Comment by ArminJo** [comment]
It is already implemented by calling requestMaxCanvasSize() at initCommunication().

**Comment by piotrcurious** [comment]
So as i understand one should call checkAndHandleEvents(); right after initCommunication?
Or call it from InitDisplay?
None of the examples is actually getting it working,
if one gets sizes in InitDisplay as in examples then they are 0

Sent from Proton Mail Android

-------- Original Message --------

**Comment by piotrcurious** [comment]
managed to get it working, obviously the resolution is only updated in the callback .
this example has it working right and it correctly changes size each time different size display is connected:
https://github.com/piotrcurious/Arduino-BlueDisplay/blob/master/examples/bt_AP2/bt_AP2.ino
