### ISSUE TITLE
Is it possible to use the BlueDisplay with the ESP32?

### ISSUE THREAD

**Issue by SuchaiNop** [ArminJo/Arduino-BlueDisplay#5]
Hi @ArminJo
I had tried to use the BlueDisplay with ESP32 and found that it could be paired to the BlueDisplay App on an Android. However, I still do not know how to send some data from the ESP32 to the App.

Please advise me.

**Comment by ArminJo** [comment]
Hi SuchaiNop
on ESP you have wlan, why do you want to use BlueDisplay?

**Comment by SuchaiNop** [comment]
I would like a smartphone to show data from the sensor and/or display them
as a graph. So students could do some scientific experiments.

regards,
Suchai

**Comment by ArminJo** [comment]
Hi Suchai,
I updated the library and examples to use BlueDisplay with an ESP32.
Please give feedback, if it works for you, I will then make a new release.

Regards
Armin

**Comment by SuchaiNop** [comment]
First of all, I really appreciate all the work you have done for my request.
It works!
By the way, I have tried to understand how it works. I then hope to be able to use/adapt/modify it to fit with my work.
