### ISSUE TITLE
Is it possible to use BlueDisplay with the Arduino Due?

### ISSUE THREAD

**Issue by EKersting** [ArminJo/Arduino-BlueDisplay#7]
Hi @ArminJo,

I am trying to use BlueDisplay on my Arduino Due, but I have some problems. (I am a total beginner in the arduino world)

Problems I encounter:

1. With BTModuleProgrammer:
While trying to load sketch onto Due:
SoftwareSerial.h: No such file or directory

I think with the DUE you don't need this library anymore, but I can't find a replacement or change the code to work without this library (somehow change some softwareserials to hardwarserial names in the code?)

2. With BlueDisplayBlink:
Loading sketch seems to be working, but some warnings, i.e.:

WARNING: library BlueDisplay claims to run on avr, esp8266, esp32, stm32, STM32 architecture(s) and may be incompatible with your current board which runs on sam architecture(s).
In file included from C:\Users\Kersting\Documents\ArduinoData\packages\arduino\hardware\sam\1.6.12\cores\arduino/Arduino.h:44:0,
                 from C:\Users\Kersting\Documents\Arduino\libraries\BlueDisplay\src\BlueSerial.h:34,
                 from C:\Users\Kersting\Documents\Arduino\libraries\BlueDisplay\src\BDSlider.cpp:34:
C:\Users\Kersting\Documents\ArduinoData\packages\arduino\hardware\sam\1.6.12\cores\arduino/wiring_constants.h:33:0: warning: "true" redefined [enabled by default]
 #define true 0x1
 ^

There are several more of the #define ones.

BlueDisplay App on my Xiaomi M8 connects to the HC05 module but then this comes:
No data received after connection. Reset Arduino and check if the baudrate of BT-Module and your program is matching.

Did not change baud rate, so both should be 9600.

3. With BlueDisplayExample:
While trying to load sketch onto Due:

Arduino: 1.8.13 (Windows Store 1.8.39.0) (Windows 10), Board: "Arduino Due (Programming Port)"

WARNING: library BlueDisplay claims to run on avr, esp8266, esp32, stm32, STM32 architecture(s) and may be incompatible with your current board which runs on sam architecture(s).

C:\Users\Kersting\Documents\Arduino\BlueDisplayExample\BlueDisplayExample.ino: In function 'void setup()':

BlueDisplayExample:178:29: error: 'tone' was not declared in this scope

     tone(TONE_PIN, 2000, 200);

                             ^

exit status 1

'tone' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

The library of the function tone() seems not to be supporting the Due. And some alternative librarys that should help with that, I cant get to work. (like https://github.com/YordanYordanovGIT/NewToneLib)

Some help or advice is really appreciated.

Best wishes,
Elmar

**Comment by ArminJo** [comment]
I will have look at this after the weekend.

**Comment by EKersting** [comment]
Any news on this @ArminJo?

**Comment by ArminJo** [comment]
Sorry, I am busy with the IR libraries, but I will reserve a slot for you.

**Comment by ArminJo** [comment]
Ok, I updated the repository with a new version.
Can you please test it and give feedback, before I release it?

**Comment by ArminJo** [comment]
Any news?
Otherwise I will build the release.

**Comment by EKersting** [comment]
I haven't got it working till now. Uploading sketches now works, but still no data received.

I think that my inexperience with arduino or such boards in general is to blame, because no other bluetooth terminal on android will work either with even the simpliest sketches (i.e. turing LED on and off), but I am slowling learning and working through tutorials :)

**Comment by ArminJo** [comment]
Tested and released.
