### ISSUE TITLE
Examples don't compile for ATmega128 

### ISSUE THREAD

**Issue by Greece2** [ArminJo/Arduino-BlueDisplay#8]
Hi, a great tool !
Unfortunately, it doesn't compile for the ATmega128 (board-lib MegaCore).
Maybe there's a chance to fix it ?  Thanks already !
Here are the messages:

Arduino: 1.8.13 (Windows 7), Board: "ATmega128, No bootloader, EEPROM retained, BOD 2.7V, LTO disabled, Internal 8 MHz"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\XYZ\AppData\Local\Arduino15\packages -hardware W:\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\XYZ\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries W:\libraries -fqbn=MegaCore:avr:128:bootloader=no_bootloader,eeprom=keep,BOD=2v7,LTO=Os,clock=8MHz_internal -ide-version=10813 -build-path C:\Users\XYZ\AppData\Local\Temp\arduino_build_410827 -warnings=all -build-cache C:\Users\XYZ\AppData\Local\Temp\arduino_cache_517068 -prefs=build.warn_data_percentage=75 -verbose W:\libraries\BlueDisplay\examples\BlueDisplayExample\BlueDisplayExample.ino

C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\XYZ\AppData\Local\Arduino15\packages -hardware W:\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\XYZ\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries W:\libraries -fqbn=MegaCore:avr:128:bootloader=no_bootloader,eeprom=keep,BOD=2v7,LTO=Os,clock=8MHz_internal -ide-version=10813 -build-path C:\Users\XYZ\AppData\Local\Temp\arduino_build_410827 -warnings=all -build-cache C:\Users\XYZ\AppData\Local\Temp\arduino_cache_517068 -prefs=build.warn_data_percentage=75 -verbose W:\libraries\BlueDisplay\examples\BlueDisplayExample\BlueDisplayExample.ino

Using board '128' from platform in folder: C:\Users\XYZ\AppData\Local\Arduino15\packages\MegaCore\hardware\avr\2.0.4

Using core 'MCUdude_corefiles' from platform in folder: C:\Users\XYZ\AppData\Local\Arduino15\packages\MegaCore\hardware\avr\2.0.4

Warning: Board breadboard:avr:atmega328bb doesn't define a 'build.board' preference. Auto-set to: AVR_ATMEGA328BB

Detecting libraries used...

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\sketch\\BlueDisplayExample.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Alternatives for BlueDisplay.h: [BlueDisplay@2.1.1]

ResolveLibrary(BlueDisplay.h)

  -> candidates: [BlueDisplay@2.1.1]

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\sketch\\BlueDisplayExample.ino.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\sketch\\Time.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\BDButton.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\BDSlider.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\BlueDisplay.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\BlueSerial.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\EventHandler.cpp" -o nul -DARDUINO_LIB_DISCOVERY_PHASE

Generating function prototypes...

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -w -x c++ -E -CC -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\sketch\\BlueDisplayExample.ino.cpp" -o "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\preproc\\ctags_target_for_gcc_minus_e.cpp" -DARDUINO_LIB_DISCOVERY_PHASE

"C:\\Program Files (x86)\\Arduino\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\preproc\\ctags_target_for_gcc_minus_e.cpp"

Sketch wird kompiliert...

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\sketch\\Time.cpp" -o "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\sketch\\Time.cpp.o"

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\sketch\\BlueDisplayExample.ino.cpp" -o "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\sketch\\BlueDisplayExample.ino.cpp.o"

Compiling libraries...

Compiling library "BlueDisplay"

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\BDSlider.cpp" -o "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\libraries\\BlueDisplay\\BDSlider.cpp.o"

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\BDButton.cpp" -o "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\libraries\\BlueDisplay\\BDButton.cpp.o"

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\BlueSerial.cpp" -o "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\libraries\\BlueDisplay\\BlueSerial.cpp.o"

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\BlueDisplay.cpp" -o "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\libraries\\BlueDisplay\\BlueDisplay.cpp.o"

In file included from c:\program files (x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\program files (x86)\arduino\hardware\tools\avr\avr\include\avr\pgmspace.h:90,

                 from W:\libraries\BlueDisplay\src\BlueDisplay.h:36,

                 from W:\libraries\BlueDisplay\src\BlueDisplay.cpp:33:

W:\libraries\BlueDisplay\src\BlueDisplay.cpp: In function 'uint16_t readADCChannelWithReferenceOversample(uint8_t, uint8_t, uint8_t)':

W:\libraries\BlueDisplay\src\BlueDisplay.cpp:1551:43: error: 'ADATE' was not declared in this scope

     ADCSRA = (_BV(ADEN) | _BV(ADSC) | _BV(ADATE) | _BV(ADIF) | ADC_PRESCALE);

                                           ^

W:\libraries\BlueDisplay\src\BlueDisplay.cpp:1551:43: note: suggested alternative: 'ADIE'

"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\EventHandler.cpp" -o "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_410827\\libraries\\BlueDisplay\\EventHandler.cpp.o"

Bibliothek BlueDisplay in Version 2.1.1 im Ordner: W:\libraries\BlueDisplay  wird verwendet

exit status 1

Fehler beim Kompilieren für das Board ATmega128.

**Comment by ArminJo** [comment]
I includes a few changes. Please try the latest version from this repository.

**Comment by Greece2** [comment]
Hi Armin,

thanks a lot !

The BTModuleProgrammer example compiles fine :-)

 

Unfortunately, the BlueDisplayExample, BlueDisplayBlink, RcCarControl still produce this error:

 


In file included from c:\program files (x86)\arduino\hardware\tools\avr\avr\include\avr\io.h:99:0,
                 from c:\program files (x86)\arduino\hardware\tools\avr\avr\include\avr\pgmspace.h:90,
                 from W:\libraries\BlueDisplay\src\BlueDisplay.h:36,
                 from W:\libraries\BlueDisplay\src\BlueDisplay.cpp:33:
W:\libraries\BlueDisplay\src\BlueDisplay.cpp: In function 'uint16_t readADCChannelWithReferenceOversample(uint8_t, uint8_t, uint8_t)':
W:\libraries\BlueDisplay\src\BlueDisplay.cpp:1551:43: error: 'ADATE' was not declared in this scope
     ADCSRA = (_BV(ADEN) | _BV(ADSC) | _BV(ADATE) | _BV(ADIF) | ADC_PRESCALE);
                                           ^
W:\libraries\BlueDisplay\src\BlueDisplay.cpp:1551:43: note: suggested alternative: 'ADIE'
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -Wall -Wextra -std=gnu++11 -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega128 -DF_CPU=8000000L -DARDUINO=10813 -DARDUINO_AVR_ATmega128 -DARDUINO_ARCH_AVR "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\cores\\MCUdude_corefiles" "-IC:\\Users\\XYZ\\AppData\\Local\\Arduino15\\packages\\MegaCore\\hardware\\avr\\2.0.4\\variants\\64-pin-avr" "-IW:\\libraries\\BlueDisplay\\src" "W:\\libraries\\BlueDisplay\\src\\EventHandler.cpp" -o "C:\\Users\\XYZ\\AppData\\Local\\Temp\\arduino_build_707404\\libraries\\BlueDisplay\\EventHandler.cpp.o"
Bibliothek BlueDisplay in Version 2.1.1 im Ordner: W:\libraries\BlueDisplay  wird verwendet
exit status 1
Fehler beim Kompilieren für das Board ATmega128.

 

Best regards and thanx for all the work !

 


 
 

Gesendet: Samstag, 12. Dezember 2020 um 22:12 Uhr
Von: "Armin" <notifications@github.com>
An: "ArminJo/Arduino-BlueDisplay" <Arduino-BlueDisplay@noreply.github.com>
Cc: "Greece2" <greece2001@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ArminJo/Arduino-BlueDisplay] Examples don't compile for ATmega128 (#8)


 

I includes a few changes. Please try the latest version from this repository.

**Comment by ArminJo** [comment]
I can not reproduce the error I know from the old version.
Are you totally sure that the BlueDispaly.cpp has this code  as lines 1650 ff.
```
1650 }
1651 #else
// dummy functions for examples
uint16_t __attribute__((weak)) readADCChannelWithReferenceOversample(uint8_t aChannelNumber, uint8_t aReference,
        uint8_t aOversampleExponent) {
    return 0;
}
float __attribute__((weak)) getTemperature(void) {
    return 0.0;
}
float __attribute__((weak)) getVCCVoltage(void) {
    return 0.0;
}
#  ifdef AVR
void BlueDisplay::printVCCAndTemperaturePeriodically(uint16_t aXPos, uint16_t aYPos, uint16_t aTextSize, uint16_t aPeriodMillis) {
}
#  endif
#endif // defined(AVR) && defined(ADCSRA) && defined(ADATE)
```

**Comment by Greece2** [comment]
No, looks very different.

I will delete all BlueDisplay files from the lib-directory, download the zip-file

and try again.

Will come back to you then. Thanks a lot for the work !

 
 

Gesendet: Sonntag, 13. Dezember 2020 um 11:29 Uhr
Von: "Armin" <notifications@github.com>
An: "ArminJo/Arduino-BlueDisplay" <Arduino-BlueDisplay@noreply.github.com>
Cc: "Greece2" <greece2001@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ArminJo/Arduino-BlueDisplay] Examples don't compile for ATmega128 (#8)


 

I can not reproduce the error I know from the old version.
Are you totally sure that the BlueDispaly.cpp has this code as lines 1650 ff.

1650 }
1651 #else
// dummy functions for examples
uint16_t __attribute__((weak)) readADCChannelWithReferenceOversample(uint8_t aChannelNumber, uint8_t aReference,
        uint8_t aOversampleExponent) {
    return 0;
}
float __attribute__((weak)) getTemperature(void) {
    return 0.0;
}
float __attribute__((weak)) getVCCVoltage(void) {
    return 0.0;
}
#  ifdef AVR
void BlueDisplay::printVCCAndTemperaturePeriodically(uint16_t aXPos, uint16_t aYPos, uint16_t aTextSize, uint16_t aPeriodMillis) {
}
#  endif
#endif // defined(AVR) && defined(ADCSRA) && defined(ADATE)

**Comment by Greece2** [comment]
Hi,

after deleting all BlueDisplay files from the lib-directories, downloading the zip-file again,

it compiles fine now :-)

Great job, thanks again !

 
 

Gesendet: Sonntag, 13. Dezember 2020 um 11:29 Uhr
Von: "Armin" <notifications@github.com>
An: "ArminJo/Arduino-BlueDisplay" <Arduino-BlueDisplay@noreply.github.com>
Cc: "Greece2" <greece2001@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [ArminJo/Arduino-BlueDisplay] Examples don't compile for ATmega128 (#8)


 

I can not reproduce the error I know from the old version.
Are you totally sure that the BlueDispaly.cpp has this code as lines 1650 ff.

1650 }
1651 #else
// dummy functions for examples
uint16_t __attribute__((weak)) readADCChannelWithReferenceOversample(uint8_t aChannelNumber, uint8_t aReference,
        uint8_t aOversampleExponent) {
    return 0;
}
float __attribute__((weak)) getTemperature(void) {
    return 0.0;
}
float __attribute__((weak)) getVCCVoltage(void) {
    return 0.0;
}
#  ifdef AVR
void BlueDisplay::printVCCAndTemperaturePeriodically(uint16_t aXPos, uint16_t aYPos, uint16_t aTextSize, uint16_t aPeriodMillis) {
}
#  endif
#endif // defined(AVR) && defined(ADCSRA) && defined(ADATE)
